GET http://localhost:3000/user-logged-in
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmFuZSIsImlhdCI6MTcxNDYzNjQ0MSwiZXhwIjoxNzE0NjM2NDkxfQ.jyA9bZQM6sSCR8BWuDP9iTyYIai3yZ7v-9eDnplobsc"
}

###

POST http://localhost:4000/getnewToken
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmFuZSIsImlhdCI6MTcxNDYzNjA4OH0.jN9lUjmaJA2nTOGcA2k14sQuwarQ3ImPcBxRtW_GOQ0"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Jane"
}

###

DELETE http://localhost:3000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}
