GET http://localhost:3000/user-logged-in
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmFuZSIsImlhdCI6MTcxNTAwODYyMCwiZXhwIjoxNzE1MDEzNjIwfQ.KflSFmu5CL6Z_vIk0A8gXa26Kf10IifDcoPu9kyCkbg

###

POST http://localhost:4000/getnewToken
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmFuZSIsImlhdCI6MTcxNTAxMDQwN30.dG0XvZNwch9Aj8dRxhJDrXjtiVnUaM-AvUk3uEkecbc"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Jane"
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmFuZSIsImlhdCI6MTcxNTAxMDQwN30.dG0XvZNwch9Aj8dRxhJDrXjtiVnUaM-AvUk3uEkecbc"
}


###

GET http://localhost:4000/users
